kind: Deployment
apiVersion: apps/v1
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: 898494379612.dkr.ecr.us-west-1.amazonaws.com/app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
