apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    run: app
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30080
    targetPort: 3000
  
  selector:
    run: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      run: app
  replicas: 1
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
      - name: app
        image: 847137928610.dkr.ecr.us-east-1.amazonaws.com/app:latest
        ports:
        - containerPort: 3000
