apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      run: app
  replicas: 1
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
      - name: app
        image: 847137928610.dkr.ecr.us-east-1.amazonaws.com/app:latest
        ports:
        - containerPort: 3000

